# Day 4 - Feature Engineering for TelecomTS

In [5]:
from datasets import load_dataset

dataset = load_dataset(
    "AliMaatouk/TelecomTS",
    data_files={"full": "**/chunked.jsonl"}
)

data = dataset["full"]

print("Total samples:", len(data))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/6.02k [00:00<?, ?B/s]

Resolving data files:   0%|          | 0/33 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/33 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/33 [00:00<?, ?files/s]

chunked.jsonl:   0%|          | 0.00/3.56M [00:00<?, ?B/s]

chunked.jsonl:   0%|          | 0.00/6.29M [00:00<?, ?B/s]

chunked.jsonl:   0%|          | 0.00/4.56M [00:00<?, ?B/s]

chunked.jsonl:   0%|          | 0.00/4.50M [00:00<?, ?B/s]

normal/mobile/File/processed/chunked.jso(…): reconstructing file:   0%|          |  0.00B / 11.6MB

normal/stationary/Zone_A/congestion/File(…): reconstructing file:   0%|          |  0.00B / 11.0MB

normal/mobile/YouTube/processed/chunked.(…): reconstructing file:   0%|          |  0.00B / 10.5MB

normal/mobile/Twitch/processed/chunked.j(…): reconstructing file:   0%|          |  0.00B / 11.5MB

chunked.jsonl:   0%|          | 0.00/3.63M [00:00<?, ?B/s]

normal/mobile/YouTube/processed/chunked.(…): downloading bytes:           |  0.00B

chunked.jsonl:   0%|          | 0.00/6.06M [00:00<?, ?B/s]

normal/stationary/Zone_A/congestion/File(…): downloading bytes:           |  0.00B

chunked.jsonl:   0%|          | 0.00/3.69M [00:00<?, ?B/s]

normal/mobile/File/processed/chunked.jso(…): downloading bytes:           |  0.00B

normal/mobile/Twitch/processed/chunked.j(…): downloading bytes:           |  0.00B

chunked.jsonl:   0%|          | 0.00/3.04M [00:00<?, ?B/s]

chunked.jsonl:   0%|          | 0.00/6.53M [00:00<?, ?B/s]

chunked.jsonl:   0%|          | 0.00/3.00M [00:00<?, ?B/s]

chunked.jsonl:   0%|          | 0.00/3.07M [00:00<?, ?B/s]

chunked.jsonl:   0%|          | 0.00/5.21M [00:00<?, ?B/s]

normal/stationary/Zone_A/congestion/Twit(…): reconstructing file:   0%|          |  0.00B / 11.1MB

normal/stationary/Zone_A/congestion/Twit(…): downloading bytes:           |  0.00B

normal/stationary/Zone_A/congestion/YouT(…): reconstructing file:   0%|          |  0.00B / 10.9MB

normal/stationary/Zone_A/no_congestion/F(…): reconstructing file:   0%|          |  0.00B /  108MB

normal/stationary/Zone_A/no_congestion/T(…): reconstructing file:   0%|          |  0.00B /  105MB

normal/stationary/Zone_A/no_congestion/Y(…): reconstructing file:   0%|          |  0.00B / 94.1MB

normal/stationary/Zone_A/congestion/YouT(…): downloading bytes:           |  0.00B

normal/stationary/Zone_B/congestion/File(…): reconstructing file:   0%|          |  0.00B / 11.1MB

normal/stationary/Zone_A/no_congestion/T(…): downloading bytes:           |  0.00B

normal/stationary/Zone_A/no_congestion/Y(…): downloading bytes:           |  0.00B

normal/stationary/Zone_A/no_congestion/F(…): downloading bytes:           |  0.00B

normal/stationary/Zone_B/congestion/Twit(…): reconstructing file:   0%|          |  0.00B / 11.0MB

normal/stationary/Zone_B/congestion/YouT(…): reconstructing file:   0%|          |  0.00B / 11.0MB

normal/stationary/Zone_B/no_congestion/F(…): reconstructing file:   0%|          |  0.00B /  108MB

normal/stationary/Zone_B/congestion/File(…): downloading bytes:           |  0.00B

normal/stationary/Zone_B/no_congestion/T(…): reconstructing file:   0%|          |  0.00B /  107MB

normal/stationary/Zone_B/congestion/Twit(…): downloading bytes:           |  0.00B

normal/stationary/Zone_B/congestion/YouT(…): downloading bytes:           |  0.00B

normal/stationary/Zone_B/no_congestion/Y(…): reconstructing file:   0%|          |  0.00B / 95.0MB

normal/stationary/Zone_B/no_congestion/F(…): downloading bytes:           |  0.00B

normal/stationary/Zone_B/no_congestion/T(…): downloading bytes:           |  0.00B

normal/stationary/Zone_B/no_congestion/Y(…): downloading bytes:           |  0.00B

normal/stationary/Zone_C/congestion/File(…): reconstructing file:   0%|          |  0.00B / 11.1MB

normal/stationary/Zone_C/congestion/File(…): downloading bytes:           |  0.00B

normal/stationary/Zone_C/congestion/Twit(…): reconstructing file:   0%|          |  0.00B / 11.0MB

normal/stationary/Zone_C/congestion/YouT(…): reconstructing file:   0%|          |  0.00B / 11.0MB

normal/stationary/Zone_C/no_congestion/T(…): reconstructing file:   0%|          |  0.00B /  108MB

normal/stationary/Zone_C/no_congestion/F(…): reconstructing file:   0%|          |  0.00B /  109MB

normal/stationary/Zone_C/congestion/Twit(…): downloading bytes:           |  0.00B

normal/stationary/Zone_C/no_congestion/F(…): downloading bytes:           |  0.00B

normal/stationary/Zone_C/no_congestion/Y(…): reconstructing file:   0%|          |  0.00B / 96.1MB

normal/stationary/Zone_C/no_congestion/T(…): downloading bytes:           |  0.00B

normal/stationary/Zone_C/congestion/YouT(…): downloading bytes:           |  0.00B

normal/stationary/Zone_C/no_congestion/Y(…): downloading bytes:           |  0.00B

Generating full split: 0 examples [00:00, ? examples/s]

Total samples: 32000

In [17]:
#inspect one sample
sample = data[0]

print(sample.keys())

dict_keys(['start_time', 'end_time', 'sampling_rate', 'KPIs', 'description', 'anomalies', 'statistics', 'labels', 'QnA'])

In [26]:
# Identify numerical KPIs
numeric_kpis = [
    "RSRP",
    "DL_BLER",
    "DL_MCS",
    "UL_BLER",
    "UL_MCS",
    "UL_NPRB",
    "UL_SNR",
    "TX_Bytes",
    "RX_Bytes",
    "Estimated_UL_Buffer",
    "PRBs_DL_Current",
    "PRBs_UL_Current",
    "PRB_Utilization_DL",
    "PRB_Utilization_UL",
    "UL_NumberOfPackets",
    "DL_NumberOfPackets"
]

print("Number of numeric KPIs:", len(numeric_kpis))

Number of numeric KPIs: 16

In [27]:
#Create the Feature Extraction Function

import numpy as np

def extract_features(sample):

    features = {}

    for kpi in numeric_kpis:

        values = np.array(sample["KPIs"][kpi])

        features[f"{kpi}_mean"] = values.mean()
        features[f"{kpi}_std"] = values.std()
        features[f"{kpi}_min"] = values.min()
        features[f"{kpi}_max"] = values.max()

    return features

In [28]:
features = extract_features(data[0])

print("Number of features:", len(features))

list(features.items())[:10]

Number of features: 64

[('RSRP_mean', np.float64(-73.232265625)),
 ('RSRP_std', np.float64(0.4956785356391372)),
 ('RSRP_min', np.float64(-75.0)),
 ('RSRP_max', np.float64(-73.0)),
 ('DL_BLER_mean', np.float64(0.010301960156249963)),
 ('DL_BLER_std', np.float64(0.015408454993070857)),
 ('DL_BLER_min', np.float64(0.0)),
 ('DL_BLER_max', np.float64(0.0597941999999999)),
 ('DL_MCS_mean', np.float64(7.0)),
 ('DL_MCS_std', np.float64(0.0))]

In [29]:
all_features = []

for i in range(len(data)):
    sample_features = extract_features(data[i])
    all_features.append(sample_features)

print("Total samples processed:", len(all_features))
print("Features per sample:", len(all_features[0]))

Total samples processed: 32000
Features per sample: 64

In [30]:
import pandas as pd

features_df = pd.DataFrame(all_features)

print("Shape:", features_df.shape)

features_df.head()

Shape: (32000, 64)

,RSRP_mean,RSRP_std,RSRP_min,RSRP_max,DL_BLER_mean,DL_BLER_std,DL_BLER_min,DL_BLER_max,DL_MCS_mean,DL_MCS_std,...,PRB_Utilization_UL_min,PRB_Utilization_UL_max,UL_NumberOfPackets_mean,UL_NumberOfPackets_std,UL_NumberOfPackets_min,UL_NumberOfPackets_max,DL_NumberOfPackets_mean,DL_NumberOfPackets_std,DL_NumberOfPackets_min,DL_NumberOfPackets_max
0,-73.232266,0.495679,-75.0,-73.0,0.010302,0.015408,0.000000,0.059794,7.0,0.0,...,0.0472,4.7924,76.273438,26.976180,20.0,189.0,282.312500,299.763807,0.0,1926.0
1,-73.000000,0.000000,-73.0,-73.0,0.008302,0.013705,0.000010,0.061595,7.0,0.0,...,0.0944,3.9341,71.070312,16.495825,32.0,131.0,270.632812,278.073587,0.0,1706.0
2,-73.000000,0.000000,-73.0,-73.0,0.011597,0.016540,0.000000,0.065248,7.0,0.0,...,0.0472,6.4814,75.921875,26.423122,18.0,195.0,298.101562,247.815261,0.0,1821.0
3,-73.143243,0.392053,-75.0,-73.0,0.013444,0.014954,0.001104,0.065243,7.0,0.0,...,0.0944,3.8395,73.875000,20.186629,39.0,177.0,283.750000,228.396961,0.0,952.0
4,-74.000000,0.000000,-74.0,-74.0,0.008212,0.014711,0.000000,0.060280,7.0,0.0,...,0.3963,4.3586,77.101562,24.352823,36.0,190.0,285.234375,242.676530,0.0,1375.0

In [31]:
print(features_df.columns.tolist())

['RSRP_mean', 'RSRP_std', 'RSRP_min', 'RSRP_max', 'DL_BLER_mean', 'DL_BLER_std', 'DL_BLER_min', 'DL_BLER_max', 'DL_MCS_mean', 'DL_MCS_std', 'DL_MCS_min', 'DL_MCS_max', 'UL_BLER_mean', 'UL_BLER_std', 'UL_BLER_min', 'UL_BLER_max', 'UL_MCS_mean', 'UL_MCS_std', 'UL_MCS_min', 'UL_MCS_max', 'UL_NPRB_mean', 'UL_NPRB_std', 'UL_NPRB_min', 'UL_NPRB_max', 'UL_SNR_mean', 'UL_SNR_std', 'UL_SNR_min', 'UL_SNR_max', 'TX_Bytes_mean', 'TX_Bytes_std', 'TX_Bytes_min', 'TX_Bytes_max', 'RX_Bytes_mean', 'RX_Bytes_std', 'RX_Bytes_min', 'RX_Bytes_max', 'Estimated_UL_Buffer_mean', 'Estimated_UL_Buffer_std', 'Estimated_UL_Buffer_min', 'Estimated_UL_Buffer_max', 'PRBs_DL_Current_mean', 'PRBs_DL_Current_std', 'PRBs_DL_Current_min', 'PRBs_DL_Current_max', 'PRBs_UL_Current_mean', 'PRBs_UL_Current_std', 'PRBs_UL_Current_min', 'PRBs_UL_Current_max', 'PRB_Utilization_DL_mean', 'PRB_Utilization_DL_std', 'PRB_Utilization_DL_min', 'PRB_Utilization_DL_max', 'PRB_Utilization_UL_mean', 'PRB_Utilization_UL_std', 'PRB_Utilization_UL_min', 'PRB_Utilization_UL_max', 'UL_NumberOfPackets_mean', 'UL_NumberOfPackets_std', 'UL_NumberOfPackets_min', 'UL_NumberOfPackets_max', 'DL_NumberOfPackets_mean', 'DL_NumberOfPackets_std', 'DL_NumberOfPackets_min', 'DL_NumberOfPackets_max']

In [32]:
target = []

for i in range(len(data)):

    label = data[i]["labels"]["anomaly_present"]

    if label == "Yes":
        target.append(1)
    else:
        target.append(0)

print("Total labels:", len(target))
print("Normal samples:", target.count(0))
print("Anomalous samples:", target.count(1))

Total labels: 32000
Normal samples: 30765
Anomalous samples: 1235

In [33]:
#Add the Target to the Feature DataFrame
features_df["target"] = target

print("Dataset shape:", features_df.shape)

Dataset shape: (32000, 65)

In [34]:
features_df.head()

,RSRP_mean,RSRP_std,RSRP_min,RSRP_max,DL_BLER_mean,DL_BLER_std,DL_BLER_min,DL_BLER_max,DL_MCS_mean,DL_MCS_std,...,PRB_Utilization_UL_max,UL_NumberOfPackets_mean,UL_NumberOfPackets_std,UL_NumberOfPackets_min,UL_NumberOfPackets_max,DL_NumberOfPackets_mean,DL_NumberOfPackets_std,DL_NumberOfPackets_min,DL_NumberOfPackets_max,target
0,-73.232266,0.495679,-75.0,-73.0,0.010302,0.015408,0.000000,0.059794,7.0,0.0,...,4.7924,76.273438,26.976180,20.0,189.0,282.312500,299.763807,0.0,1926.0,1
1,-73.000000,0.000000,-73.0,-73.0,0.008302,0.013705,0.000010,0.061595,7.0,0.0,...,3.9341,71.070312,16.495825,32.0,131.0,270.632812,278.073587,0.0,1706.0,1
2,-73.000000,0.000000,-73.0,-73.0,0.011597,0.016540,0.000000,0.065248,7.0,0.0,...,6.4814,75.921875,26.423122,18.0,195.0,298.101562,247.815261,0.0,1821.0,1
3,-73.143243,0.392053,-75.0,-73.0,0.013444,0.014954,0.001104,0.065243,7.0,0.0,...,3.8395,73.875000,20.186629,39.0,177.0,283.750000,228.396961,0.0,952.0,1
4,-74.000000,0.000000,-74.0,-74.0,0.008212,0.014711,0.000000,0.060280,7.0,0.0,...,4.3586,77.101562,24.352823,36.0,190.0,285.234375,242.676530,0.0,1375.0,1

In [35]:
features_df["target"].value_counts()

target
0    30765
1     1235
Name: count, dtype: int64

In [36]:
#Check for Missing Values
missing_values = features_df.isnull().sum()

print("Total missing values:", missing_values.sum())

Total missing values: 0

In [38]:
#Check for Duplicate Rows
duplicate_count = features_df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [39]:
#Check Feature Data Types
print(features_df.dtypes.value_counts())

float64    64
int64       1
Name: count, dtype: int64

In [40]:
features_df.describe()

,RSRP_mean,RSRP_std,RSRP_min,RSRP_max,DL_BLER_mean,DL_BLER_std,DL_BLER_min,DL_BLER_max,DL_MCS_mean,DL_MCS_std,...,PRB_Utilization_UL_max,UL_NumberOfPackets_mean,UL_NumberOfPackets_std,UL_NumberOfPackets_min,UL_NumberOfPackets_max,DL_NumberOfPackets_mean,DL_NumberOfPackets_std,DL_NumberOfPackets_min,DL_NumberOfPackets_max,target
count,32000.000000,32000.000000,32000.000000,32000.000000,32000.000000,32000.000000,32000.000000,32000.000000,32000.000000,32000.000000,...,32000.000000,32000.000000,32000.000000,32000.000000,32000.000000,32000.000000,32000.000000,32000.000000,32000.000000,32000.000000
mean,-106.160735,0.442309,-107.106175,-105.402793,0.091257,0.017262,0.070347,0.128338,6.832511,0.051113,...,4.667869,30.069669,11.543660,8.187799,71.164210,104.091821,68.717866,5.987664,395.386745,0.038594
std,10.525186,0.964300,10.817488,10.609121,0.265294,0.064190,0.248398,0.309955,0.481092,0.235402,...,6.446726,94.209004,53.087094,37.473204,202.727287,150.129485,93.057146,55.511037,490.606456,0.192628
min,-135.940984,0.000000,-141.000000,-133.820520,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.047200,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-114.467131,0.000000,-116.000000,-114.000000,0.000000,0.000000,0.000000,0.000000,7.000000,0.000000,...,2.575500,0.875000,2.526387,0.000000,17.000000,5.171875,4.373802,0.000000,23.000000,0.000000
50%,-110.000000,0.145773,-111.000000,-109.000000,0.000078,0.000137,0.000000,0.000808,7.000000,0.000000,...,3.490600,21.335938,10.739848,0.000000,63.000000,59.234375,36.046917,0.000000,223.000000,0.000000
75%,-102.000000,0.470815,-102.000000,-102.000000,0.001905,0.002857,0.000000,0.015984,7.000000,0.000000,...,4.698000,52.525391,14.982894,5.000000,97.000000,231.822266,89.918869,0.000000,411.000000,0.000000
max,-72.953125,16.589033,-73.000000,-48.000000,1.015150,0.500600,1.002230,1.181638,7.190859,3.498291,...,100.000000,7107.832722,4426.864189,4165.761873,10647.079925,6535.432273,3159.787911,5352.926956,9663.379462,1.000000

In [41]:
print("Final ML dataset")
print("----------------")
print("Samples:", features_df.shape[0])
print("Features:", features_df.shape[1] - 1)
print("Target column:", "target")
print("Normal samples:", (features_df["target"] == 0).sum())
print("Anomalous samples:", (features_df["target"] == 1).sum())
print("Missing values:", features_df.isnull().sum().sum())
print("Duplicate rows:", features_df.duplicated().sum())

Final ML dataset
----------------
Samples: 32000
Features: 64
Target column: target
Normal samples: 30765
Anomalous samples: 1235
Missing values: 0
Duplicate rows: 0

In [42]:
import os

os.makedirs("data/processed", exist_ok=True)

print("Processed data folder ready.")

Processed data folder ready.

In [43]:
output_path = "data/processed/telecom_features.csv"

features_df.to_csv(output_path, index=False)

print("Saved:", output_path)

Saved: data/processed/telecom_features.csv

In [44]:
import os

print("File exists:", os.path.exists(output_path))

if os.path.exists(output_path):
    print(
        "File size:",
        round(os.path.getsize(output_path) / (1024 * 1024), 2),
        "MB"
    )

File exists: True
File size: 20.5 MB

## Day 4 Summary

Today, the TelecomTS time-series data was transformed into a machine learning-ready feature dataset.

For each of the 16 numerical KPI variables, four statistical features were extracted:

- Mean
- Standard deviation
- Minimum
- Maximum

This produced 64 numerical features for each sample.

The anomaly label was converted into a binary target:

- 0 = Normal
- 1 = Anomaly

The final dataset contains 32,000 samples and 64 input features with one target column. Basic data-quality checks were also performed, including missing-value and duplicate-row checks.

The processed feature dataset was saved as `telecom_features.csv` for use in subsequent machine learning experiments.